version: "3.8"

services:
  rekruto:
    container_name: rekruto
    build: ./backend
    command: flask run --host=0.0.0.0 --port=8000
    ports:
      - 8000:8000
    environment:
      - FLASK_APP=server.py
    working_dir: /app
    restart: on-failure